// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: rent.proto

package rent

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartRentRequest struct {
	state         protoimpl.MessageState
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BikeId        string `protobuf:"bytes,2,opt,name=bike_id,json=bikeId,proto3" json:"bike_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRentRequest) Reset() {
	*x = StartRentRequest{}
	mi := &file_rent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRentRequest) ProtoMessage() {}

func (x *StartRentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StartRentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StartRentRequest) GetBikeId() string {
	if x != nil {
		return x.BikeId
	}
	return ""
}

type EndRentRequest struct {
	state         protoimpl.MessageState
	RentId        string `protobuf:"bytes,1,opt,name=rent_id,json=rentId,proto3" json:"rent_id,omitempty"`
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndRentRequest) Reset() {
	*x = EndRentRequest{}
	mi := &file_rent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndRentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndRentRequest) ProtoMessage() {}

func (x *EndRentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EndRentRequest) GetRentId() string {
	if x != nil {
		return x.RentId
	}
	return ""
}

func (x *EndRentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RentResponse struct {
	state         protoimpl.MessageState
	RentId        string `protobuf:"bytes,1,opt,name=rent_id,json=rentId,proto3" json:"rent_id,omitempty"`
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BikeId        string `protobuf:"bytes,3,opt,name=bike_id,json=bikeId,proto3" json:"bike_id,omitempty"`
	Status        string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Message       string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	StartTime     int64  `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64  `protobuf:"varint,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RentResponse) Reset() {
	*x = RentResponse{}
	mi := &file_rent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RentResponse) ProtoMessage() {}

func (x *RentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RentResponse) GetRentId() string {
	if x != nil {
		return x.RentId
	}
	return ""
}

func (x *RentResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RentResponse) GetBikeId() string {
	if x != nil {
		return x.BikeId
	}
	return ""
}

func (x *RentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RentResponse) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *RentResponse) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type AvailableBikesRequest struct {
	state         protoimpl.MessageState
	Location      string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableBikesRequest) Reset() {
	*x = AvailableBikesRequest{}
	mi := &file_rent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableBikesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableBikesRequest) ProtoMessage() {}

func (x *AvailableBikesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AvailableBikesRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type Bike struct {
	state         protoimpl.MessageState
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Location      string `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bike) Reset() {
	*x = Bike{}
	mi := &file_rent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bike) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bike) ProtoMessage() {}

func (x *Bike) ProtoReflect() protoreflect.Message {
	mi := &file_rent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Bike) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bike) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bike) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Bike) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type BikesList struct {
	state         protoimpl.MessageState
	Bikes         []*Bike `protobuf:"bytes,1,rep,name=bikes,proto3" json:"bikes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BikesList) Reset() {
	*x = BikesList{}
	mi := &file_rent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BikesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BikesList) ProtoMessage() {}

func (x *BikesList) ProtoReflect() protoreflect.Message {
	mi := &file_rent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BikesList) GetBikes() []*Bike {
	if x != nil {
		return x.Bikes
	}
	return nil
}

type StatsRequest struct {
	state         protoimpl.MessageState
	Date          string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_rent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StatsRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type StatsResponse struct {
	state         protoimpl.MessageState
	Date          string            `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	TotalRents    int64             `protobuf:"varint,2,opt,name=total_rents,json=totalRents,proto3" json:"total_rents,omitempty"`
	ActiveRents   int64             `protobuf:"varint,3,opt,name=active_rents,json=activeRents,proto3" json:"active_rents,omitempty"`
	LocationStats  map[string]int64 `protobuf:"bytes,4,rep,name=location_stats,json=locationStats,proto3" json:"location_stats,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_rent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StatsResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *StatsResponse) GetTotalRents() int64 {
	if x != nil {
		return x.TotalRents
	}
	return 0
}

func (x *StatsResponse) GetActiveRents() int64 {
	if x != nil {
		return x.ActiveRents
	}
	return 0
}

func (x *StatsResponse) GetLocationStats() map[string]int64 {
	if x != nil {
		return x.LocationStats
	}
	return nil
}

var File_rent_proto protoreflect.FileDescriptor

var file_rent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_rent_proto_goTypes = []interface{}{
	(*StartRentRequest)(nil),    // 0: rent.StartRentRequest
	(*EndRentRequest)(nil),       // 1: rent.EndRentRequest
	(*RentResponse)(nil),         // 2: rent.RentResponse
	(*AvailableBikesRequest)(nil), // 3: rent.AvailableBikesRequest
	(*Bike)(nil),                // 4: rent.Bike
	(*BikesList)(nil),           // 5: rent.BikesList
	(*StatsRequest)(nil),         // 6: rent.StatsRequest
	(*StatsResponse)(nil),        // 7: rent.StatsResponse
}
var file_rent_proto_depIdxs = []int32{
	4, // 0: rent.BikesList.bikes:type_name -> rent.Bike
	1, // [1:1] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rent_proto_init() }
func file_rent_proto_init() {
	if File_rent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartRentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndRentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndRentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvailableBikesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bike); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BikesList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rent_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rent_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: []byte{},
		},
		GoTypes:           file_rent_proto_goTypes,
		DependencyIndexes: file_rent_proto_depIdxs,
		MessageInfos:      file_rent_proto_msgTypes,
	}.Build()
	File_rent_proto = out.File
	file_rent_proto_rawDesc = nil
	file_rent_proto_goTypes = nil
}

var (
	file_rent_proto_rawDesc []byte
)
