// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// 	protoc-gen-go-grpc v1.5.1
// 	protoc        v6.32.0
// source: rent.proto

package rent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// RentServiceClient is the client API for RentService service.
type RentServiceClient interface {
	StartRent(ctx context.Context, in *StartRentRequest, opts ...grpc.CallOption) (*RentResponse, error)
	EndRent(ctx context.Context, in *EndRentRequest, opts ...grpc.CallOption) (*RentResponse, error)
	GetAvailableBikes(ctx context.Context, in *AvailableBikesRequest, opts ...grpc.CallOption) (*BikesList, error)
	GetRentStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type rentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRentServiceClient(cc grpc.ClientConnInterface) RentServiceClient {
	return &rentServiceClient{cc}
}

func (c *rentServiceClient) StartRent(ctx context.Context, in *StartRentRequest, opts ...grpc.CallOption) (*RentResponse, error) {
	out := new(RentResponse)
	err := c.cc.Invoke(ctx, "/rent.RentService/StartRent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentServiceClient) EndRent(ctx context.Context, in *EndRentRequest, opts ...grpc.CallOption) (*RentResponse, error) {
	out := new(RentResponse)
	err := c.cc.Invoke(ctx, "/rent.RentService/EndRent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentServiceClient) GetAvailableBikes(ctx context.Context, in *AvailableBikesRequest, opts ...grpc.CallOption) (*BikesList, error) {
	out := new(BikesList)
	err := c.cc.Invoke(ctx, "/rent.RentService/GetAvailableBikes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentServiceClient) GetRentStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, "/rent.RentService/GetRentStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RentServiceServer is the server API for RentService service.
type RentServiceServer interface {
	StartRent(context.Context, *StartRentRequest) (*RentResponse, error)
	EndRent(context.Context, *EndRentRequest) (*RentResponse, error)
	GetAvailableBikes(context.Context, *AvailableBikesRequest) (*BikesList, error)
	GetRentStats(context.Context, *StatsRequest) (*StatsResponse, error)
	mustEmbedUnimplementedRentServiceServer()
}

type UnimplementedRentServiceServer struct {
}

func (UnimplementedRentServiceServer) StartRent(context.Context, *StartRentRequest) (*RentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartRent not implemented")
}
func (UnimplementedRentServiceServer) EndRent(context.Context, *EndRentRequest) (*RentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndRent not implemented")
}
func (UnimplementedRentServiceServer) GetAvailableBikes(context.Context, *AvailableBikesRequest) (*BikesList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailableBikes not implemented")
}
func (UnimplementedRentServiceServer) GetRentStats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRentStats not implemented")
}
func (UnimplementedRentServiceServer) mustEmbedUnimplementedRentServiceServer() {}

func RegisterRentServiceServer(s grpc.ServiceRegistrar, srv RentServiceServer) {
	s.RegisterService(&RentService_ServiceDesc, srv)
}

func _RentService_StartRent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentServiceServer).StartRent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rent.RentService/StartRent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentServiceServer).StartRent(ctx, req.(*StartRentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentService_EndRent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndRentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentServiceServer).EndRent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rent.RentService/EndRent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentServiceServer).EndRent(ctx, req.(*EndRentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentService_GetAvailableBikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AvailableBikesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentServiceServer).GetAvailableBikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rent.RentService/GetAvailableBikes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentServiceServer).GetAvailableBikes(ctx, req.(*AvailableBikesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentService_GetRentStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentServiceServer).GetRentStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rent.RentService/GetRentStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentServiceServer).GetRentStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var RentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rent.RentService",
	HandlerType: (*RentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRent",
			Handler:    _RentService_StartRent_Handler,
		},
		{
			MethodName: "EndRent",
			Handler:    _RentService_EndRent_Handler,
		},
		{
			MethodName: "GetAvailableBikes",
			Handler:    _RentService_GetAvailableBikes_Handler,
		},
		{
			MethodName: "GetRentStats",
			Handler:    _RentService_GetRentStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rent.proto",
}

