// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: models/student_model.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StudentsInfoModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Age           uint64                 `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentsInfoModel) Reset() {
	*x = StudentsInfoModel{}
	mi := &file_models_student_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentsInfoModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentsInfoModel) ProtoMessage() {}

func (x *StudentsInfoModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_student_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentsInfoModel.ProtoReflect.Descriptor instead.
func (*StudentsInfoModel) Descriptor() ([]byte, []int) {
	return file_models_student_model_proto_rawDescGZIP(), []int{0}
}

func (x *StudentsInfoModel) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StudentsInfoModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StudentsInfoModel) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *StudentsInfoModel) GetAge() uint64 {
	if x != nil {
		return x.Age
	}
	return 0
}

type StudentsUpsertModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Age           uint64                 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentsUpsertModel) Reset() {
	*x = StudentsUpsertModel{}
	mi := &file_models_student_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentsUpsertModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentsUpsertModel) ProtoMessage() {}

func (x *StudentsUpsertModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_student_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentsUpsertModel.ProtoReflect.Descriptor instead.
func (*StudentsUpsertModel) Descriptor() ([]byte, []int) {
	return file_models_student_model_proto_rawDescGZIP(), []int{1}
}

func (x *StudentsUpsertModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StudentsUpsertModel) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *StudentsUpsertModel) GetAge() uint64 {
	if x != nil {
		return x.Age
	}
	return 0
}

var File_models_student_model_proto protoreflect.FileDescriptor

const file_models_student_model_proto_rawDesc = "" +
	"\n" +
	"\x1amodels/student_model.proto\x12\x12students.models.v1\"_\n" +
	"\x11StudentsInfoModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x04R\x03age\"Q\n" +
	"\x13StudentsUpsertModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x04R\x03ageB5Z3github.com/Domenick1991/students/internal/pb/modelsb\x06proto3"

var (
	file_models_student_model_proto_rawDescOnce sync.Once
	file_models_student_model_proto_rawDescData []byte
)

func file_models_student_model_proto_rawDescGZIP() []byte {
	file_models_student_model_proto_rawDescOnce.Do(func() {
		file_models_student_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_student_model_proto_rawDesc), len(file_models_student_model_proto_rawDesc)))
	})
	return file_models_student_model_proto_rawDescData
}

var file_models_student_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_models_student_model_proto_goTypes = []any{
	(*StudentsInfoModel)(nil),   // 0: students.models.v1.StudentsInfoModel
	(*StudentsUpsertModel)(nil), // 1: students.models.v1.StudentsUpsertModel
}
var file_models_student_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_student_model_proto_init() }
func file_models_student_model_proto_init() {
	if File_models_student_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_student_model_proto_rawDesc), len(file_models_student_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_student_model_proto_goTypes,
		DependencyIndexes: file_models_student_model_proto_depIdxs,
		MessageInfos:      file_models_student_model_proto_msgTypes,
	}.Build()
	File_models_student_model_proto = out.File
	file_models_student_model_proto_goTypes = nil
	file_models_student_model_proto_depIdxs = nil
}
