// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: students_api/students.proto

package students_api

import (
	models "github.com/Domenick1991/students/internal/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStudentInfoByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentInfoByIDsRequest) Reset() {
	*x = GetStudentInfoByIDsRequest{}
	mi := &file_students_api_students_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentInfoByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentInfoByIDsRequest) ProtoMessage() {}

func (x *GetStudentInfoByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_students_api_students_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentInfoByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetStudentInfoByIDsRequest) Descriptor() ([]byte, []int) {
	return file_students_api_students_proto_rawDescGZIP(), []int{0}
}

func (x *GetStudentInfoByIDsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetStudentInfoByIDsResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	StudentInfos  []*models.StudentsInfoModel `protobuf:"bytes,1,rep,name=studentInfos,proto3" json:"studentInfos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentInfoByIDsResponse) Reset() {
	*x = GetStudentInfoByIDsResponse{}
	mi := &file_students_api_students_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentInfoByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentInfoByIDsResponse) ProtoMessage() {}

func (x *GetStudentInfoByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_students_api_students_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentInfoByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetStudentInfoByIDsResponse) Descriptor() ([]byte, []int) {
	return file_students_api_students_proto_rawDescGZIP(), []int{1}
}

func (x *GetStudentInfoByIDsResponse) GetStudentInfos() []*models.StudentsInfoModel {
	if x != nil {
		return x.StudentInfos
	}
	return nil
}

type GetStudentInfoUpsertRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Students      []*models.StudentsUpsertModel `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentInfoUpsertRequest) Reset() {
	*x = GetStudentInfoUpsertRequest{}
	mi := &file_students_api_students_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentInfoUpsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentInfoUpsertRequest) ProtoMessage() {}

func (x *GetStudentInfoUpsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_students_api_students_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentInfoUpsertRequest.ProtoReflect.Descriptor instead.
func (*GetStudentInfoUpsertRequest) Descriptor() ([]byte, []int) {
	return file_students_api_students_proto_rawDescGZIP(), []int{2}
}

func (x *GetStudentInfoUpsertRequest) GetStudents() []*models.StudentsUpsertModel {
	if x != nil {
		return x.Students
	}
	return nil
}

type GetStudentInfoUpsertResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentInfoUpsertResponce) Reset() {
	*x = GetStudentInfoUpsertResponce{}
	mi := &file_students_api_students_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentInfoUpsertResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentInfoUpsertResponce) ProtoMessage() {}

func (x *GetStudentInfoUpsertResponce) ProtoReflect() protoreflect.Message {
	mi := &file_students_api_students_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentInfoUpsertResponce.ProtoReflect.Descriptor instead.
func (*GetStudentInfoUpsertResponce) Descriptor() ([]byte, []int) {
	return file_students_api_students_proto_rawDescGZIP(), []int{3}
}

var File_students_api_students_proto protoreflect.FileDescriptor

const file_students_api_students_proto_rawDesc = "" +
	"\n" +
	"\x1bstudents_api/students.proto\x12\x13students.service.v1\x1a\x1amodels/student_model.proto\x1a\x1cgoogle/api/annotations.proto\".\n" +
	"\x1aGetStudentInfoByIDsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\"h\n" +
	"\x1bGetStudentInfoByIDsResponse\x12I\n" +
	"\fstudentInfos\x18\x01 \x03(\v2%.students.models.v1.StudentsInfoModelR\fstudentInfos\"b\n" +
	"\x1bGetStudentInfoUpsertRequest\x12C\n" +
	"\bstudents\x18\x01 \x03(\v2'.students.models.v1.StudentsUpsertModelR\bstudents\"\x1e\n" +
	"\x1cGetStudentInfoUpsertResponce2\xcc\x02\n" +
	"\x0fStudentsService\x12\x9c\x01\n" +
	"\x13GetStudentInfoByIDs\x12/.students.service.v1.GetStudentInfoByIDsRequest\x1a0.students.service.v1.GetStudentInfoByIDsResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/studentInfo/get-by-ids\x12\x99\x01\n" +
	"\x12UpsertStudentInfos\x120.students.service.v1.GetStudentInfoUpsertRequest\x1a1.students.service.v1.GetStudentInfoUpsertResponce\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/studentInfo/upsertB;Z9github.com/Domenick1991/students/internal/pb/students_apib\x06proto3"

var (
	file_students_api_students_proto_rawDescOnce sync.Once
	file_students_api_students_proto_rawDescData []byte
)

func file_students_api_students_proto_rawDescGZIP() []byte {
	file_students_api_students_proto_rawDescOnce.Do(func() {
		file_students_api_students_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_students_api_students_proto_rawDesc), len(file_students_api_students_proto_rawDesc)))
	})
	return file_students_api_students_proto_rawDescData
}

var file_students_api_students_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_students_api_students_proto_goTypes = []any{
	(*GetStudentInfoByIDsRequest)(nil),   // 0: students.service.v1.GetStudentInfoByIDsRequest
	(*GetStudentInfoByIDsResponse)(nil),  // 1: students.service.v1.GetStudentInfoByIDsResponse
	(*GetStudentInfoUpsertRequest)(nil),  // 2: students.service.v1.GetStudentInfoUpsertRequest
	(*GetStudentInfoUpsertResponce)(nil), // 3: students.service.v1.GetStudentInfoUpsertResponce
	(*models.StudentsInfoModel)(nil),     // 4: students.models.v1.StudentsInfoModel
	(*models.StudentsUpsertModel)(nil),   // 5: students.models.v1.StudentsUpsertModel
}
var file_students_api_students_proto_depIdxs = []int32{
	4, // 0: students.service.v1.GetStudentInfoByIDsResponse.studentInfos:type_name -> students.models.v1.StudentsInfoModel
	5, // 1: students.service.v1.GetStudentInfoUpsertRequest.students:type_name -> students.models.v1.StudentsUpsertModel
	0, // 2: students.service.v1.StudentsService.GetStudentInfoByIDs:input_type -> students.service.v1.GetStudentInfoByIDsRequest
	2, // 3: students.service.v1.StudentsService.UpsertStudentInfos:input_type -> students.service.v1.GetStudentInfoUpsertRequest
	1, // 4: students.service.v1.StudentsService.GetStudentInfoByIDs:output_type -> students.service.v1.GetStudentInfoByIDsResponse
	3, // 5: students.service.v1.StudentsService.UpsertStudentInfos:output_type -> students.service.v1.GetStudentInfoUpsertResponce
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_students_api_students_proto_init() }
func file_students_api_students_proto_init() {
	if File_students_api_students_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_students_api_students_proto_rawDesc), len(file_students_api_students_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_students_api_students_proto_goTypes,
		DependencyIndexes: file_students_api_students_proto_depIdxs,
		MessageInfos:      file_students_api_students_proto_msgTypes,
	}.Build()
	File_students_api_students_proto = out.File
	file_students_api_students_proto_goTypes = nil
	file_students_api_students_proto_depIdxs = nil
}
