// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: students_api/students.proto

package students_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StudentsService_GetStudentInfoByIDs_FullMethodName = "/students.service.v1.StudentsService/GetStudentInfoByIDs"
	StudentsService_UpsertStudentInfos_FullMethodName  = "/students.service.v1.StudentsService/UpsertStudentInfos"
)

// StudentsServiceClient is the client API for StudentsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StudentsServiceClient interface {
	GetStudentInfoByIDs(ctx context.Context, in *GetStudentInfoByIDsRequest, opts ...grpc.CallOption) (*GetStudentInfoByIDsResponse, error)
	UpsertStudentInfos(ctx context.Context, in *GetStudentInfoUpsertRequest, opts ...grpc.CallOption) (*GetStudentInfoUpsertResponce, error)
}

type studentsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStudentsServiceClient(cc grpc.ClientConnInterface) StudentsServiceClient {
	return &studentsServiceClient{cc}
}

func (c *studentsServiceClient) GetStudentInfoByIDs(ctx context.Context, in *GetStudentInfoByIDsRequest, opts ...grpc.CallOption) (*GetStudentInfoByIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStudentInfoByIDsResponse)
	err := c.cc.Invoke(ctx, StudentsService_GetStudentInfoByIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentsServiceClient) UpsertStudentInfos(ctx context.Context, in *GetStudentInfoUpsertRequest, opts ...grpc.CallOption) (*GetStudentInfoUpsertResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStudentInfoUpsertResponce)
	err := c.cc.Invoke(ctx, StudentsService_UpsertStudentInfos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudentsServiceServer is the server API for StudentsService service.
// All implementations must embed UnimplementedStudentsServiceServer
// for forward compatibility.
type StudentsServiceServer interface {
	GetStudentInfoByIDs(context.Context, *GetStudentInfoByIDsRequest) (*GetStudentInfoByIDsResponse, error)
	UpsertStudentInfos(context.Context, *GetStudentInfoUpsertRequest) (*GetStudentInfoUpsertResponce, error)
	mustEmbedUnimplementedStudentsServiceServer()
}

// UnimplementedStudentsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStudentsServiceServer struct{}

func (UnimplementedStudentsServiceServer) GetStudentInfoByIDs(context.Context, *GetStudentInfoByIDsRequest) (*GetStudentInfoByIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentInfoByIDs not implemented")
}
func (UnimplementedStudentsServiceServer) UpsertStudentInfos(context.Context, *GetStudentInfoUpsertRequest) (*GetStudentInfoUpsertResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertStudentInfos not implemented")
}
func (UnimplementedStudentsServiceServer) mustEmbedUnimplementedStudentsServiceServer() {}
func (UnimplementedStudentsServiceServer) testEmbeddedByValue()                         {}

// UnsafeStudentsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StudentsServiceServer will
// result in compilation errors.
type UnsafeStudentsServiceServer interface {
	mustEmbedUnimplementedStudentsServiceServer()
}

func RegisterStudentsServiceServer(s grpc.ServiceRegistrar, srv StudentsServiceServer) {
	// If the following call pancis, it indicates UnimplementedStudentsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StudentsService_ServiceDesc, srv)
}

func _StudentsService_GetStudentInfoByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentInfoByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentsServiceServer).GetStudentInfoByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentsService_GetStudentInfoByIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentsServiceServer).GetStudentInfoByIDs(ctx, req.(*GetStudentInfoByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentsService_UpsertStudentInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentInfoUpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentsServiceServer).UpsertStudentInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentsService_UpsertStudentInfos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentsServiceServer).UpsertStudentInfos(ctx, req.(*GetStudentInfoUpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StudentsService_ServiceDesc is the grpc.ServiceDesc for StudentsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StudentsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "students.service.v1.StudentsService",
	HandlerType: (*StudentsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStudentInfoByIDs",
			Handler:    _StudentsService_GetStudentInfoByIDs_Handler,
		},
		{
			MethodName: "UpsertStudentInfos",
			Handler:    _StudentsService_UpsertStudentInfos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "students_api/students.proto",
}
