// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Domenick1991/students/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewStudentStorage creates a new instance of StudentStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStudentStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *StudentStorage {
	mock := &StudentStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StudentStorage is an autogenerated mock type for the StudentStorage type
type StudentStorage struct {
	mock.Mock
}

type StudentStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *StudentStorage) EXPECT() *StudentStorage_Expecter {
	return &StudentStorage_Expecter{mock: &_m.Mock}
}

// GetStudentInfoByIDs provides a mock function for the type StudentStorage
func (_mock *StudentStorage) GetStudentInfoByIDs(ctx context.Context, IDs []uint64) ([]*models.StudentInfo, error) {
	ret := _mock.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for GetStudentInfoByIDs")
	}

	var r0 []*models.StudentInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint64) ([]*models.StudentInfo, error)); ok {
		return returnFunc(ctx, IDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint64) []*models.StudentInfo); ok {
		r0 = returnFunc(ctx, IDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.StudentInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uint64) error); ok {
		r1 = returnFunc(ctx, IDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StudentStorage_GetStudentInfoByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStudentInfoByIDs'
type StudentStorage_GetStudentInfoByIDs_Call struct {
	*mock.Call
}

// GetStudentInfoByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uint64
func (_e *StudentStorage_Expecter) GetStudentInfoByIDs(ctx interface{}, IDs interface{}) *StudentStorage_GetStudentInfoByIDs_Call {
	return &StudentStorage_GetStudentInfoByIDs_Call{Call: _e.mock.On("GetStudentInfoByIDs", ctx, IDs)}
}

func (_c *StudentStorage_GetStudentInfoByIDs_Call) Run(run func(ctx context.Context, IDs []uint64)) *StudentStorage_GetStudentInfoByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uint64
		if args[1] != nil {
			arg1 = args[1].([]uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StudentStorage_GetStudentInfoByIDs_Call) Return(studentInfos []*models.StudentInfo, err error) *StudentStorage_GetStudentInfoByIDs_Call {
	_c.Call.Return(studentInfos, err)
	return _c
}

func (_c *StudentStorage_GetStudentInfoByIDs_Call) RunAndReturn(run func(ctx context.Context, IDs []uint64) ([]*models.StudentInfo, error)) *StudentStorage_GetStudentInfoByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertStudentInfo provides a mock function for the type StudentStorage
func (_mock *StudentStorage) UpsertStudentInfo(ctx context.Context, studentInfos []*models.StudentInfo) error {
	ret := _mock.Called(ctx, studentInfos)

	if len(ret) == 0 {
		panic("no return value specified for UpsertStudentInfo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*models.StudentInfo) error); ok {
		r0 = returnFunc(ctx, studentInfos)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StudentStorage_UpsertStudentInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertStudentInfo'
type StudentStorage_UpsertStudentInfo_Call struct {
	*mock.Call
}

// UpsertStudentInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - studentInfos []*models.StudentInfo
func (_e *StudentStorage_Expecter) UpsertStudentInfo(ctx interface{}, studentInfos interface{}) *StudentStorage_UpsertStudentInfo_Call {
	return &StudentStorage_UpsertStudentInfo_Call{Call: _e.mock.On("UpsertStudentInfo", ctx, studentInfos)}
}

func (_c *StudentStorage_UpsertStudentInfo_Call) Run(run func(ctx context.Context, studentInfos []*models.StudentInfo)) *StudentStorage_UpsertStudentInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*models.StudentInfo
		if args[1] != nil {
			arg1 = args[1].([]*models.StudentInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StudentStorage_UpsertStudentInfo_Call) Return(err error) *StudentStorage_UpsertStudentInfo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StudentStorage_UpsertStudentInfo_Call) RunAndReturn(run func(ctx context.Context, studentInfos []*models.StudentInfo) error) *StudentStorage_UpsertStudentInfo_Call {
	_c.Call.Return(run)
	return _c
}
