// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"context"

	"bike-rental/rent-service/internal/models"

	"github.com/google/uuid"
	"github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetAvailableBikes provides a mock function with given fields: ctx, location
func (_m *Repository) GetAvailableBikes(ctx context.Context, location string) ([]models.Bike, error) {
	ret := _m.Called(ctx, location)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableBikes")
	}

	var r0 []models.Bike
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Bike, error)); ok {
		return rf(ctx, location)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Bike); ok {
		r0 = rf(ctx, location)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Bike)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, location)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBikeByID provides a mock function with given fields: ctx, bikeID
func (_m *Repository) GetBikeByID(ctx context.Context, bikeID uuid.UUID) (*models.Bike, error) {
	ret := _m.Called(ctx, bikeID)

	if len(ret) == 0 {
		panic("no return value specified for GetBikeByID")
	}

	var r0 *models.Bike
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Bike, error)); ok {
		return rf(ctx, bikeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Bike); ok {
		r0 = rf(ctx, bikeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Bike)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, bikeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StartRent provides a mock function with given fields: ctx, userID, bikeID
func (_m *Repository) StartRent(ctx context.Context, userID string, bikeID uuid.UUID) (*models.Rent, error) {
	ret := _m.Called(ctx, userID, bikeID)

	if len(ret) == 0 {
		panic("no return value specified for StartRent")
	}

	var r0 *models.Rent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) (*models.Rent, error)); ok {
		return rf(ctx, userID, bikeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) *models.Rent); ok {
		r0 = rf(ctx, userID, bikeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Rent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, bikeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EndRent provides a mock function with given fields: ctx, rentID, userID
func (_m *Repository) EndRent(ctx context.Context, rentID uuid.UUID, userID string) (*models.Rent, error) {
	ret := _m.Called(ctx, rentID, userID)

	if len(ret) == 0 {
		panic("no return value specified for EndRent")
	}

	var r0 *models.Rent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*models.Rent, error)); ok {
		return rf(ctx, rentID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *models.Rent); ok {
		r0 = rf(ctx, rentID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Rent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, rentID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRentByID provides a mock function with given fields: ctx, rentID
func (_m *Repository) GetRentByID(ctx context.Context, rentID uuid.UUID) (*models.Rent, error) {
	ret := _m.Called(ctx, rentID)

	if len(ret) == 0 {
		panic("no return value specified for GetRentByID")
	}

	var r0 *models.Rent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Rent, error)); ok {
		return rf(ctx, rentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Rent); ok {
		r0 = rf(ctx, rentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Rent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, rentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBikeStatus provides a mock function with given fields: ctx, bikeID, status
func (_m *Repository) UpdateBikeStatus(ctx context.Context, bikeID uuid.UUID, status string) error {
	ret := _m.Called(ctx, bikeID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBikeStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, bikeID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddBike provides a mock function with given fields: ctx, name, location
func (_m *Repository) AddBike(ctx context.Context, name, location string) (*models.Bike, error) {
	ret := _m.Called(ctx, name, location)

	if len(ret) == 0 {
		panic("no return value specified for AddBike")
	}

	var r0 *models.Bike
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.Bike, error)); ok {
		return rf(ctx, name, location)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.Bike); ok {
		r0 = rf(ctx, name, location)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Bike)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, location)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBike provides a mock function with given fields: ctx, bikeID
func (_m *Repository) DeleteBike(ctx context.Context, bikeID uuid.UUID) error {
	ret := _m.Called(ctx, bikeID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBike")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, bikeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HasActiveRent provides a mock function with given fields: ctx, bikeID
func (_m *Repository) HasActiveRent(ctx context.Context, bikeID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, bikeID)

	if len(ret) == 0 {
		panic("no return value specified for HasActiveRent")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(ctx, bikeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, bikeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, bikeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
